name: Lint
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - run: pip install --upgrade pip
    - run: pip install "black<23" mypy pep8
    - run: black --line-length 79 --check .
    - run: flake .
    - run: mypy --strict .
    - run: pep8 .
